# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "George Welch"
description: > # this means to ignore newlines until "email:"
   Web Developer - Clean Coder

email: furiousg3org3@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'George Welch'
author: 'George Welch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/furiousg3org3
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Georgew
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	envelope
    url:	mailto:furiousg3org3@gmail.com
    desc:	Email Me
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
